print("verificando por erros")
raise Exception("erro fatal, bot n√£o funciona neste computador...")
